server:
  port: 4003

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/spring_pos_authservice
    username: springuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
